/// @file scanner.h
/// @brief Header file associated to scanner.y

#ifndef SCANNER_H
#define SCANNER_H

#include <stdio.h>

extern int lineNum;

/* This global variable is the file read by the Flex-generated scanner */
extern FILE *yyin;

/* yylex() is the function generated by Flex that returns a the next token
 * scanned from the input. */
int yylex(void);

#endif
